### ISSUE TITLE
Protonation in Drawings

### ISSUE THREAD

**Issue by jaketanderson** [PeterEckmann1/limo-webserver#1]
https://github.com/PeterEckmann1/limo-webserver/blob/23a0a4777ca7c6e6fb0300c0a72cc7c711820d24/main.py#L57-L62

Currently, the workflow is SMILES (implicit Hs) -> RDKit -> Image. What I suggest is using the attached workflow instead for better protonation in the drawings. I'm not sure if creating an RDKit molecule from an expicit-H SMILES string will maintain that protonation, so I wrote two branches.

![diagram](https://user-images.githubusercontent.com/95603449/226748452-1f2133cb-4fcb-4533-90b0-aabc463f0015.png)

**Comment by PeterEckmann1** [comment]
Thanks, I updated the live version of the code to use obabel's `-p 7.0` flag.
